### ISSUE TITLE
how to generate and preview?

### ISSUE THREAD

**Issue by rexdf** [octopress/octopress#100]
How can I generate the `_post` into `_site`? I do not find any hint in readme.

The command line octopress is much slower than before. I need to wait at least 20+ seconds to get result for `octopress --help`

**Comment by imathis** [comment]
You should use the Jekyll commands, `jekyll build` or `jekyll build --watch`. `jekyll server` boots up a server at localhost:4000 where you can preview your site. Use `jekyll --help` to learn more.

Regarding speed:

This is probably because of the number of gems you have installed. It takes ruby gems a while to boot up. If you're using bundler in your site, running `bundle exec octopress --help` will execute much faster. If not, you can run `gem cleanup` which will remove all but the latest versions of your gems and then your system won't take as long looking through your many gems.
