### ISSUE TITLE
Can/should I use octopress 3 or 2?

### ISSUE THREAD

**Issue by idiazroncero** [octopress/octopress#113]
Hi there;

I am planning on making a blog for myself, and looking for solutions other than database-powered CMSs I found your amazing project. It is perfect for my needs. Congratulations on your work!

I read your [blog post at Octopress.org] (http://octopress.org/2015/01/15/octopress-3.0-is-coming/) and i thought 3.0 wasn't still ready, but then I realized the post's date is January. Then I visited this repo (and Octopress Ink's repo) and I'm not clear about the current stage of the project. From the outside, 3.0 seems pretty solid and, according to [this issue] (https://github.com/octopress/octopress/issues/55), only pagination and docs are missing.

The question is: is octopress 3 mature enough to develop a blog, style a theme and host everything on a apache-powered server? Or should I better stick with 2 and then migrate when 3 is ready?

I am leaned towards using 3 and thus avoid learning a version soon to be outdated. I am not in a hurry. I have time to confront the lack of documentation and learn by testing. Even, if it is of any help, I could give you some feedback on my experience as a developer and user. Should I do this?

**Comment by VirusKA** [comment]
3.0 is offically released

**Comment by imathis** [comment]
My Octopress 2 support is basically done now. I'll occasionally work on fixes for it, but it has very little of my attention. Octopress 3 embraces the future of Jekyll and is much easier for me to maintain. My ticket turnaround time is typically really fast since everything is broken up into separate projects. The only drawback for Octopress 3 right now is the lack of themes. That's something I'm working on at [octopress-genesis-theme](https://github.com/octopress/genesis-theme) and with the [octopress-ink](https://github.com/octopress/ink) framework, but for now if you're interested in having a stock theme, Octopnress 3 can't help you yet.
