### ISSUE TITLE
Draft is visible on deployed site

### ISSUE THREAD

**Issue by bvosk** [octopress/octopress#167]
I can't find it explicitly said in the documentation, but aren't files in the `_drafts` folder supposed to be hidden when I deploy my site? When I run `octopress deploy`, I can see my drafts _and_ posts up on the live site.

Here is what the directories look like. All three of these posts get deployed:

```
_posts
├── 2016-02-08-init.md
└── 2016-06-07-nerves.md

_drafts
└── nerves-blinky.md
```

**Comment by plttn** [comment]
AFAIK `octopress deploy` doesn't rebuild the site, so if they were in `_site` when you ran it, it'll sync it up. Do a `jekyll build` to clear the drafts from site, then deploy and it should be fine.

**Comment by cloudrck** [comment]
[octopress deploy](https://github.com/octopress/octopress#deploying-your-site) doesn't build anything.

jekyll build will build based on your configuration.

So files in _drafts should not be built. I'm not sure what your deployment configuration consist of, but if the files are on the server live than it may have been because they were published at one point. You have to remove them.

**Comment by bvosk** [comment]
Thanks to both of you! I'm about to go to sleep, but it sounds like this will fix my problem.

**Comment by cloudrck** [comment]
I have a small script in each of my projects I execute when I want to sync.

``` shell
jekyll build
octopress deploy
```

**Comment by parkr** [comment]
@plttn @cloudrck :heart:
