### ISSUE TITLE
Confusing install instructions github vs octopress.org

### ISSUE THREAD

**Issue by ramonsuarez** [octopress/octopress#179]
First> thanks a lot for developing Octopress and putting so much work in the benefit of all.

I guess the octopress.org does not get updated as much as this repository. The problem for new users like me is that there are different install instructions in octopress.org and github.com/octopress/octopress. 
Which is the good one? The folder structure is different between the cloned repo and using octopress new project (which is much simpler and does not have the same files). I'm running into gem problems and not knowing which install method is good is not helping. Having a tree list of a vanilla Octopress project would be helpful to check if our install is right.

**Comment by deg0nz** [comment]
You should read the [blog post about Octopress 3](http://octopress.org/2015/01/15/octopress-3.0-is-coming/).

The Octopress in this repository is very different from the one described on [octopress.org](http://octopress.org), since many things have changed between version 2 and 3. 

So if you use the version here, you're on Octopress 3, which means you should use the instructions from the `readme.md` in this repo.

If you use the old Octopress from [this repo](https://github.com/imathis/octopress), you should follow the instructions on octopress.org.

**Comment by ramonsuarez** [comment]
Thanks @deg0nz . I did read the post when I first visited the page and it made me think that Octopress development was abandoned, as it is almost 2 years old and there's no post confirming the arrival of Octopress 3. If browsed it again now. There's no explanation of the different repositories/ install methods in the post. 

To make it clear for future visitors, It should be explained on the site (new post saying that 3 is here) and github, pointing users to the right install depending on what they want to install (although I don't see why se the deprecated version). Just say that the website is for historic purposes and point everybody to Github! :)
