### ISSUE TITLE
“How to get started” doc

### ISSUE THREAD

**Issue by jaanus** [octopress/octopress#66]
I gave Octopress 3 a spin. (I’m a happy Octopress 2 user, but not a Jekyll or Ruby expert by any means.) I managed to get it installed, but not sure what to do next. In an empty folder, I can generate some post markdown files with `octopress new post` command, but it is not clear how those turn into pages.

As a user, I’m expecting to follow a set of instructions that help me get started from scratch and don’t assume any prior knowledge about Jekyll or anything else. The steps would be roughly like this…

* Install (already partly covered by current readme… it covers installing the octopress command, but not how to init a site. What’s the difference between `octopress init` and `octopress new`?)
* Create and edit a new page/post (sort of covered, I could figure it out based on readme)
* Build the site HTML (missing. If I didn’t do `init` or `new`, I just have a `_posts` folder by this point. How does that turn into HTML?)
* Serve a site preview
* Load the site from a localhost URL in the browser and see something that looks like a site.

**Comment by imathis** [comment]
@jaanus I'm working on a gem based theming system called Octopress Ink. It will allow users to simply install a gem, and generate a blog with a theme. The framework is basically done, but I'm still working on building the first theme at http://github.com/octopress/genesis.

Moving forward Octopress is being split out into many different components. This should make it much easier to develop, contribute to and customize. In 2.0, Octopress expects you to learn the Octopress way of doing things. It's very much like Jekyll but it is just enough different that it has created an unnecessary division in the communities. Jekyll has grown a whole lot since the 2.0 release and in 3.0 Octopress will be 100% compatible with any Jekyll site. This means that to learn how to do most things, you'll be learning Jekyll. If you're trying to figure out how to configure a plugin, you'll be referring to the documentation for that specific plugin, not wading through documentation on Octopress.org hoping that your question will be answered.

Once I have finished the Genesis theme, I'll be working on a migration guide that will help users of Octopress 2.0 transition to the new system.

**Comment by imathis** [comment]
I should say, this is already part of the release plans, so this issue doesn't need to remain open. Feel free to continue discussion.

**Comment by chrissimpkins** [comment]
thanks much Brandon.   look forward to it.
