### ISSUE TITLE
Set "published": true (or remove "published" variable)

### ISSUE THREAD

**Issue by hazzik** [octopress/octopress#74]
Set "published": true (or remove "published" variable)
If the post has been unpublished (published: false) in frontmatter and we want to publish it, then we need to set "published": true (or remove "published" variable)

**Comment by imathis** [comment]
Are asking to be able to publish a post in the _posts folder by changing the yaml front-matter? The current publish system is designed for use of the new `_drafts/` directory feature.

If I'm right, (hey @parkr?) I think `published: false` is the legacy way of doing drafts. Perhaps I can create a command to convert a post in `_posts/` to a draft in `_drafts/` because converting a post to a draft is a pain, compared to adding `published: false`, but using drafts is a better workflow otherwise.

What do you think?

**Comment by imathis** [comment]
I have pull request #75 ready for review. This will allow you to type something like: `octopress unpublish 'some post' and it will move it into the drafts folder for you. You can read more about how this works in the PR. But I think it's preferable to setting messing with the published var.

**Comment by parkr** [comment]
It is the old way. There's an `unpublished` key you can use to show them. But it's deprecated.

https://github.com/jekyll/jekyll/blob/master/lib/jekyll/publisher.rb#L14
